#!/bin/bash

brew update
brew upgrade

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install coreutils
brew install moreutils
brew install findutils
brew install gnu-sed --with-default-names
brew install grep

# Install Bash 4
brew install bash
brew install zsh

brew install vim
brew install neovim

brew install git
brew install tig
brew install imagemagick
brew install node
brew install tree
brew install --HEAD universal-ctags/universal-ctags/universal-ctags
brew install ripgrep
brew install fd
brew install fzf

brew cask install hyper
brew cask install kitty
brew cask install flux
brew cask install slack
brew cask install spectacle
brew cask install spotify
brew cask install sequel-pro
brew cask install appcleaner
brew cask install skitch
brew cask install dropbox
brew cask install snappy
brew cask install google-chrome
brew cask install opera
brew cask install firefox

brew tap caskroom/fonts
brew cask install font-fira-code

brew tap thoughtbot/formulae
brew install rcm

brew tap crisidev/homebrew-chunkwm
brew install --HEAD --with-tmp-logging chunkwm
brew install --HEAD --with-logging koekeishiya/formulae/skhd
brew services start chunkwm
brew services start skhd

brew cleanup
