#!/bin/bash

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils

# Install Bash 4
brew install bash

brew install vim
brew install neovim
brew install fzf

brew install ack
brew install the_silver_searcher
brew install git
brew install tig
brew install imagemagick
brew install node
brew install tree
brew install tmux

brew cask install hyper
brew cask install flux
brew cask install slack
brew cask install spectacle
brew cask install spotify
brew cask install sequel-pro
brew cask install appcleaner
brew cask install skitch
brew cask install dropbox
brew cask install snappy
brew cask install google-chrome
brew cask install opera
brew cask install firefox
